"""
Database package for Smart Control System.
"""
from .database import (
    get_db_connection,
    get_db_cursor,
    init_db,
    get_all_devices,
    get_device,
    update_desired_state,
    update_current_state,
    log_sensor_reading,
    log_control_action,
    get_sensor_history,
    get_control_history,
    log_vision_event,
    get_recent_vision_events,
    create_reservation,
    get_reservations,
    get_reservation_by_pin,
    update_reservation_status,
    get_all_songs,
    get_favorite_songs,
    record_song,
)

__all__ = [
    "get_db_connection",
    "get_db_cursor",
    "init_db",
    "get_all_devices",
    "get_device",
    "update_desired_state",
    "update_current_state",
    "log_sensor_reading",
    "log_control_action",
    "get_sensor_history",
    "get_control_history",
    "log_vision_event",
    "get_recent_vision_events",
    "create_reservation",
    "get_reservations",
    "get_reservation_by_pin",
    "update_reservation_status",
    "get_all_songs",
    "get_favorite_songs",
    "record_song",
]
